export const errorCodes = {
  0: 'Email is already taken',
  1: 'Incorrect email',
  2: 'Can not create user',
  3: 'Incorrect phone number',
  4: 'Phone is already taken',
  5: 'User not found',
  6: '2FA is require',
  7: 'Invalid 2FA code',
  8: 'User is locked out',
  9: 'User is not allowed',
  10: 'Refresh token error',
  11: 'You need to verify your email or phone',
  12: 'Max count of attempts',
  13: 'Verification code expired',
  14: 'Email doesnt exists',
  15: 'Link has been expired',
  16: 'Old password is invalid',
  17: 'Change password error',
  18: 'Change password error',
  19: 'Google Auth code is invalid',
  20: 'Wallet address is already exists',
  21: 'Max 3 wallets per one user and currency',
  22: 'Incorrect password'
}