export const GET_BTC_BALANCE = 'GET_BTC_BALANCE';
export const GET_USD_BALANCE = 'GET_USD_BALANCE';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY'
export const GET_WALLETS = 'GET_WALLETS'

//DICE
export const GET_DICE_HASH = 'GET_DICE_HASH'
export const START_DICE_SUCCESS = 'START_DICE_SUCCESS'

//HILO
export const GET_HILO_HASH = 'GET_HILO_HASH'
export const START_HILO_SUCCESS = 'START_HILO_SUCCESS'

//ERRORS
export const UPDATE_ERROR_MESSAGE = 'UPDATE_ERROR_MESSAGE'

//MODALS
export const OPEN_MODAL_HANDLER = 'OPEN_MODAL_HANDLER'
export const OPEN_ERROR_MODAL_HANDLER = 'OPEN_ERROR_MODAL_HANDLER'
export const CLOSE_MODAL_HANDLER = 'CLOSE_MODAL_HANDLER'