//APPLICATION
export const LOADER_VISIBILITY = 'LOADER_VISIBILITY'

//BALANCE
export const GET_BTC_BALANCE = 'GET_BTC_BALANCE';
export const GET_CURRENT_RATE = 'GET_CURRENT_RATE'
export const GET_USD_BALANCE = 'GET_USD_BALANCE';;
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY'
export const GET_WALLETS = 'GET_WALLETS'
export const GET_PAYMENT_HISTORY = 'GET_PAYMENT_HISTORY'
export const GET_PAYMENT_PROOF = 'GET_PAYMENT_PROOF'

//DICE
export const GET_DICE_HASH = 'GET_DICE_HASH'
export const START_DICE_SUCCESS = 'START_DICE_SUCCESS'
export const GET_DICE_HISTORY = 'GET_DICE_HISTORY'

//HILO
export const GET_HILO_HASH = 'GET_HILO_HASH'
export const START_HILO_SUCCESS = 'START_HILO_SUCCESS'
export const GET_HILO_HISTORY = 'GET_HILO_HISTORY'

//ROULETTE
export const GET_ROULETTE_GAME = 'GET_ROULETTE_GAME'
export const UPDATE_ROULETTE = 'UPDATE_ROULETTE'
export const GET_ROULETTE_RESULT = 'GET_ROULETTE_RESULT'
export const GET_MIN_ORDER = 'GET_MIN_ORDER'

//FAUCET
export const GET_FAUCET_HISTORY = 'GET_FAUCET_HISTORY'
export const GET_FAUCET_WINS = 'GET_FAUCET_WINS'
export const GET_FAUCET_TIMEOUT = 'GET_FAUCET_TIMEOUT'
export const ROLL_FAUCET = 'ROLL_FAUCET'

//ERRORS
export const UPDATE_ERROR_MESSAGE = 'UPDATE_ERROR_MESSAGE'

//MODALS
export const OPEN_MODAL_HANDLER = 'OPEN_MODAL_HANDLER'
export const OPEN_ERROR_MODAL_HANDLER = 'OPEN_ERROR_MODAL_HANDLER'
export const CLOSE_MODAL_HANDLER = 'CLOSE_MODAL_HANDLER'

//STATS
export const GET_STATS = 'GET_STATS'
export const UPDATE_STATS = 'UPDATE_STATS'
export const GET_RATING = 'GET_RATING'

//PROFILE
export const GET_PROFILE_INFO = 'GET_PROFILE_INFO';
export const GET_REFERRALS = 'GET_REFERRALS';
export const GET_REFERRALS_STATISTIC = 'GET_REFERRALS_STATISTIC'
export const GET_USER_STATS = 'GET_USER_STATS'
export const GET_NICKNAME_VISIBILITY = 'GET_NICKNAME_VISIBILITY';
export const GET_AVATAR = 'GET_AVATAR';
export const GET_REFERRAL_LINK = 'GET_REFERRAL_LINK'
export const GET_MESSAGES = 'GET_MESSAGES'